### ISSUE TITLE
Auto crash (help,please)

### ISSUE THREAD

**Issue by DongShaoNB** [codehz/ElementZero#10]
![Screenshot_2020_0401_131427](https://user-images.githubusercontent.com/54093566/78113326-28357400-7432-11ea-9266-61319dace371.jpg)

**Comment by codehz** [comment]
(can you try to launch it with vanilla bds?

**Comment by DongShaoNB** [comment]
Players break down when they play captains

**Comment by DongShaoNB** [comment]
wait,i trying

**Comment by DongShaoNB** [comment]
Still not.

**Comment by codehz** [comment]
So it is vanilla bug, you should report it to bugs.mojang.com

**Comment by DongShaoNB** [comment]
ok.thanks you
