### ISSUE TITLE
Economy commands have broken description and output. (On beta)

### ISSUE THREAD

**Issue by elijahr2411** [codehz/ElementZero#102]
Although in the 1.16 progress (#99) it says that economy is complete, all of the economy commands have a broken description.
Also, executing /balance returns` command.balance.success`, get-balance returns `commands.get-balance.success`, and update-balance returns nothing.

Tested on CI #446

**Comment by Weissnix4711** [comment]
You're missing the translation pack. You're actually seeing placeholders instead of the proper description.

See [this wiki page](https://github.com/Element-0/ElementZero/wiki/Installing-and-using-the-translation-resource-pack). The pack itself is [here](https://github.com/Element-0/Translation).

**Comment by Weissnix4711** [comment]
If you have any further questions, just reply and I'll reopen the issue for you.

Good luck. :wink:
