### ISSUE TITLE
Unable to Start Server - Linux

### ISSUE THREAD

**Issue by AlexWright1324** [codehz/ElementZero#105]
[log.txt](https://github.com/Element-0/ElementZero/files/4836538/log.txt)
Haven't a clue why it isn't running
`WINEDLLOVERRIDES="vcruntime140_1,vcruntime140=n; mscoree,mshtml,explorer.exe,winemenubuilder.exe,services.exe,playplug.exe=d" WINEDEBUG=-all wine64 bedrock_server_mod.exe
`
After running without winedebug there are tons of:

> 00c4:fixme:msvcrt:MSVCRT__stdio_common_vsprintf_s options 24 not handled

**Comment by Meisoner** [comment]
Run it using docker...

**Comment by lightyisreal** [comment]
@Duncan494
![image](https://user-images.githubusercontent.com/45460688/85851133-6e3e7180-b7ae-11ea-979e-5b03c29c4f0c.png)

**Comment by AlexWright1324** [comment]
Same errors then?

**Comment by elijahr2411** [comment]
@ItzLightyHD You should probably open your own issue as you're on windows and OP is on Linux.

**Comment by AlexWright1324** [comment]
However it seems the user is using ssh into Linux so the issue is similar

**Comment by elijahr2411** [comment]
> However it seems the user is using ssh into Linux so the issue is similar

Oh, I didnt see that before.

**Comment by lemonka** [comment]
+1 - what it is needed to push it forward? I mean - some logs or what?

**Comment by truaddict** [comment]
@Duncan494 Have you finally managed to start the server?

**Comment by truaddict** [comment]
@lemonka wine version, linux distro name. And as it was said earlier in this thread it is recommended to go docker way.

**Comment by lemonka** [comment]
Hi @truaddict 
It looks like latest mcbe server and element mod are running well. At least empty server is running - Tomorrow I will check if after connection everything is ok

Wine:
```
# apt list --installed | grep wine
wine-devel-amd64/focal,now 5.15~focal amd64
wine-devel-i386/focal,now 5.15~focal i386
wine-devel/focal,now 5.15~focal amd64
winehq-devel/focal,now 5.15~focal amd64
```

Linux Mint 20:
```
# uname -a
Linux PC-SERVER 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

ElementZero-v0.1.0-testing-2-win64.tar.zst -> https://github.com/Element-0/ElementZero/releases/tag/v0.1.0-testing-2
bedrock-server-1.16.20.03.zip -> https://minecraft.azureedge.net/bin-linux/bedrock-server-1.16.20.03.zip

Runned with command 
```
# WINEDLLOVERRIDES="vcruntime140_1,vcruntime140=n; mscoree,mshtml,explorer.exe,winemenubuilder.exe,services.exe,playplug.exe=d" WINEDEBUG=-all wine64 bedrock_server_mod.exe
```

Install dir is suplemented with additional files:
```
-rw-r--r-- 1 xx xx  44320 Apr 17 09:57 vcruntime140_1.dll
-rw-r--r-- 1 xx xx 100880 Apr 17 09:57 vcruntime140.dll
```

**Comment by truaddict** [comment]
@lemonka Glad to hear that you are fine now.

**Comment by AlexWright1324** [comment]
[crash.txt](https://github.com/Element-0/ElementZero/files/5108027/crash.txt)
Seems to have something to do with msvcp
