### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by valkedev** [codehz/ElementZero#11]
I get this when trying to run on Ubuntu 18
![image](https://user-images.githubusercontent.com/1539181/78289344-b42ac700-752a-11ea-8019-e7139382b25e.png)

**Comment by valkedev** [comment]
Running good on Windows 10

**Comment by codehz** [comment]
You need install https://aka.ms/vs/16/release/VC_redist.x64.exe and run winecfg to set vcruntime140_1 as native
