### ISSUE TITLE
Hidden seed?

### ISSUE THREAD

**Issue by Meisoner** [codehz/ElementZero#111]

**Comment by Weissnix4711** [comment]
What's the question?

Yeah, seeds are hidden (as far as I know) to members, and only visible to operators. That's to do with how Bedrock edition works.

Edit: Never mind. I checked, and yes. Seeds are visible to non-OPs.

**Comment by truaddict** [comment]
There was HiddenSeed mod for old versions of EZ. But it isn't working anymore. I will try to find mod's author and ask him if he could update his mod to work with actual EZ.

**Comment by truaddict** [comment]
Seed is hidden from non-OPs in 1.16.
