### ISSUE TITLE
How to use sqlite3 from scripting API?

### ISSUE THREAD

**Issue by Weissnix4711** [codehz/ElementZero#112]
How do I use [this](https://github.com/Element-0/ElementZero/blob/master/BuiltinMods/ScriptingSupport/apiset/sqlite3.cpp) in custom scripts?

Sorry if I'm being dumb.

Does anyone have any example of how to use it? I can't understand the c++ it is written in, so I have no idea what functions to use / what arguments they take.

**Comment by truaddict** [comment]
Nice example of using sqlite3 from scripting API is here. I am sure you have seen this already, but it is for others having the same question.

https://github.com/tomrhollis/Scripts-for-EZ/blob/master/land.js

**Comment by Weissnix4711** [comment]
Yeah, I've figured it out ages ago.

I thought I had closed this already. Guess I didn't. :/
