### ISSUE TITLE
Is it simple enough to make element zero compatible with bedrock v1.12? 

### ISSUE THREAD

**Issue by ambiennt** [codehz/ElementZero#117]
Sorry if I seem ignorant in asking such a large-scale question, but I would realistically only need the experimental and education mods out of elementzero in 1.12, which I presume to be small mods. The first release of this software dates back to February, but 1.13 has been around since october of the prior year. Is it simple enough to make the software with just those two mods compatible with bedrock dedicated server software for 1.12.1? If so, could someone maybe direct me on how to do this? 

Again, I understand that I might be asking for a lot here, but please let me know where my request stands in terms of feasibility. Thanks!

**Comment by truaddict** [comment]
Have you seen https://github.com/codehz/StoneServer? It is exactly for 1.12 if I remember it right. I doubt someone will adapt current EZ to 1.12, sorry.
