### ISSUE TITLE
i want to create minigame server, should i use pocketmine or bds and this

### ISSUE THREAD

**Issue by rjworks** [codehz/ElementZero#123]

**Comment by CvldYT** [comment]
Pocketmine would be the best. No plugins for mini-games exist for EZ.

**Comment by rjworks** [comment]
what if i make my own how do performance differ?

**Comment by Weissnix4711** [comment]
PMMP still out performs EZ.

It also depends what minigames you want. If you want UHC or something, you might want to go with EZ. PMMP's terrain generation and mob spawning is very weird.

If you want to do skywars, or something like that, then I would recommend PMMP. Also, PMMP has a multi world plugin. Something which EZ doesn't have, yet.

**Comment by ambiennt** [comment]
> PMMP still out performs EZ.
> 
> It also depends what minigames you want. If you want UHC or something, you might want to go with EZ. PMMP's terrain generation and mob spawning is very weird.
> 
> If you want to do skywars, or something like that, then I would recommend PMMP. Also, PMMP has a multi world plugin. Something which EZ doesn't have, yet.

there is also nukkit, but it doesnt support behavior packs :/. I do UHC and its tough on EZ if im being honest because it doesnt perform as well with more players, but plugins wouldnt make much sense and I dont believe theres a way to load in a custom world either afaik.
