### ISSUE TITLE
The compiled code appears

### ISSUE THREAD

**Issue by mclk623** [codehz/ElementZero#124]
undefined symbol: __declspec(dllimport) public: class BlockSource & __cdecl Actor::getRegion(void) const	C:\Users\Administrator\Desktop\ElementZero\CMakeLists.txt	C:\Users\Administrator\Desktop\ElementZero\lld-link	1

**Comment by Weissnix4711** [comment]
What BDS version are you compiling for?

**Comment by mclk623** [comment]
1.16.1

**Comment by Weissnix4711** [comment]
> 1.16.1

EZ won't compile for 1.16.1. CodeHz is already aware of this.

Youll have to either compile for 1.16.0 or have a look at #115. Note that the latter still has a few issues. Most notably, scripting API is broken.

**Comment by mclk623** [comment]
Delete SpawnProtection to compile
