### ISSUE TITLE
**Why the scripts dosn't work for me?**

### ISSUE THREAD

**Issue by Charmantroll** [codehz/ElementZero#133]
Help, the scripts folder did not appear to me so I created it in the root of the bds where I have the bedrock_server_mod.exe, but I think the scripts do not work, I have it activated in custom.yaml

**Comment by Weissnix4711** [comment]
The scripts folder is not automatically created. You are correct to create it yourself.

The entry point is a file called `index.js`. It must exist in the scripts folder.

From this file, you can import other scripts. The scripting API supports ES Modules. Use the following:

```javascript
import "./scriptName.js";
import "./anotherScript.js";
```

**Comment by FateForWindows** [comment]
in addition to the above, keep in mind that scripting is currently broken on 1.16.1 and above.

**Comment by Weissnix4711** [comment]
> in addition to the above, keep in mind that scripting is currently broken on 1.16.1 and above.

Use the tag 200626 and you'll be fine.

**Comment by Charmantroll** [comment]
i am in tag 200626 and it still doesn't work for me, I think I'm wrong, in the installation, the ElementZero should be in a separate folder in the root of the BDS and the dist combined with the root of the BDS? or must be mixed, is that the installation instructions are not very clear to me

**Comment by Redbeanw44602** [comment]
They must be mixed or they will not work. Are you using the build in action? The latest build does not seem to take effect in the js engine in 1.16.1. Look at the log output by the server.

**Comment by Weissnix4711** [comment]
Closing for now as I presume the original issue has been solved.
