### ISSUE TITLE
Was the transferserver command missing, removed or did I just forget something

### ISSUE THREAD

**Issue by kishaner** [codehz/ElementZero#134]

**Comment by madeofstown** [comment]
What build of EZ are you using?

**Comment by tomrhollis** [comment]
@kishaner Did you enable transferserver in custom.yaml?

**Comment by kishaner** [comment]
> What build of EZ are you using?
#457

**Comment by kishaner** [comment]
> @kishaner Did you enable transferserver in custom.yaml?

I dont see transferserver do I have to add it manually?

**Comment by madeofstown** [comment]
Post your custom.yaml file and I can change it for you. Or it's under the essentials commands section if you want to enable it yourself.

**Comment by kishaner** [comment]
> Post your custom.yaml file and I can change it for you. Or it's under the essentials commands section if you want to enable it yourself.

OK here it is. Thanks for your help.
[custom.zip](https://github.com/Element-0/ElementZero/files/5041699/custom.zip)

**Comment by madeofstown** [comment]
```
mod-enabled: true
mod-default-enabled: false
log-settings:
  format: "%6$s %1$c [%2$s] (%3$s:%4$d) %5$s"
  database: log.db
  hide-verbose: false
  filters: []
  verbose:
    before: ""
    after: ""
  information:
    before: ""
    after: ""
  warning:
    before: ""
    after: ""
  error:
    before: ""
    after: ""
  unknown:
    before: ""
    after: ""
mods:
  Audit:
    enabled: false
  BasicAntiCheat:
    enabled: false
  Blacklist:
    enabled: false
  BossBarSupport:
    enabled: false
  Bus:
    enabled: false
  ChatAPI:
    enabled: false
  CommandSupport:
    enabled: true
  CrashHandler:
    enabled: false
  CustomScoreboard:
    enabled: false
  DebugTool:
    enabled: false
  DynamicMotd:
    enabled: false
  Economy:
    enabled: false
  Essentials:
    enabled: true
    commands:
        transferserver: true
  Experimental:
    enabled: false
  FlatWorld:
    enabled: false
  NetworkStatus:
    enabled: false
  NoEncryption:
    enabled: false
  NullPlayerData:
    enabled: false
  PacketDumper:
    enabled: false
  ScriptingSupport:
    enabled: false
  SpawnProtection:
    enabled: false
  Remote:
    enabled: false
  SignCommand:
    enabled: false
user-database: user.db
```

**Comment by madeofstown** [comment]
After you run your world after updating the custom.yaml, close it and check the custom.yaml again and you will see more options under the Essentials section.

**Comment by kishaner** [comment]
> ```
> mod-enabled: true
> mod-default-enabled: false
> log-settings:
>   format: "%6$s %1$c [%2$s] (%3$s:%4$d) %5$s"
>   database: log.db
>   hide-verbose: false
>   filters: []
>   verbose:
>     before: ""
>     after: ""
>   information:
>     before: ""
>     after: ""
>   warning:
>     before: ""
>     after: ""
>   error:
>     before: ""
>     after: ""
>   unknown:
>     before: ""
>     after: ""
> mods:
>   Audit:
>     enabled: false
>   BasicAntiCheat:
>     enabled: false
>   Blacklist:
>     enabled: false
>   BossBarSupport:
>     enabled: false
>   Bus:
>     enabled: false
>   ChatAPI:
>     enabled: false
>   CommandSupport:
>     enabled: true
>   CrashHandler:
>     enabled: false
>   CustomScoreboard:
>     enabled: false
>   DebugTool:
>     enabled: false
>   DynamicMotd:
>     enabled: false
>   Economy:
>     enabled: false
>   Essentials:
>     enabled: true
>     commands:
>         transferserver: true
>   Experimental:
>     enabled: false
>   FlatWorld:
>     enabled: false
>   NetworkStatus:
>     enabled: false
>   NoEncryption:
>     enabled: false
>   NullPlayerData:
>     enabled: false
>   PacketDumper:
>     enabled: false
>   ScriptingSupport:
>     enabled: false
>   SpawnProtection:
>     enabled: false
>   Remote:
>     enabled: false
>   SignCommand:
>     enabled: false
> user-database: user.db
> ```

thanks it worked
