### ISSUE TITLE
How do I download the most recent code as a release?

### ISSUE THREAD

**Issue by ambiennt** [codehz/ElementZero#137]
The last release was quite some time ago, and now with 1.16.20 released, it isnt compatible with any other 1.16 versions. So, im looking for a full release with the new changes.

**Comment by Redbeanw44602** [comment]
ElementZero has actually been updated to 1.16.20. You can see github action The stupid vcpkg hinders the compilation. Everyone is waiting for Microsoft to fix it.

**Comment by Weissnix4711** [comment]
Check the commit history. The little tick or cross means it has either passed all checks (compiled) or has failed (hasn't compiled).

The latest version which does compile is #87333a0e5ea44f24455df1b4a4c9504aa387b2ca. Click the little check icon, and it will take you to the actions page. From there, dowload the `dist` file.

Note: This is for bedrock version 1.16.20.01 (Not 1.16.20.03).

I still wouldn't recommend using any 1.16.20.x version yet, at all. Stick to tag 200626. It works, and it works well. Obviously wont work on the latest game version, but it's not too old. There's also a good chance many players haven't updated to 1.16.20 yet.

Edit: or indeed just go straight to the [actions](https://github.com/Element-0/ElementZero/actions) tab. It's probably easier.
