### ISSUE TITLE
The /warp list only shows global warps

### ISSUE THREAD

**Issue by Seggie1313** [codehz/ElementZero#139]
When we do /warp list, it only shows our global warps. I know that I personally have over 30 warps set and I can't remember them all. However, warps are still able to be warped to and we can set new ones. We just can't see them.
![Minecraft_2020-08-13-02-01-56](https://user-images.githubusercontent.com/67473556/90099791-488f0c80-dd09-11ea-9d3a-964c21c1ac71.jpg)

**Comment by Redbeanw44602** [comment]
I don't understand what you mean, in fact /warp should display global landmarks.

**Comment by Seggie1313** [comment]
We don't see our personal warps. Like, I have more set. I set a /warp to spawner, for instance, and it doesn't show up when I do /warp list.

**Comment by Redbeanw44602** [comment]
I think the warp plugin of ez does not provide the function of personal warp. It gives the player wrong instructions. This is a bug.

**Comment by Seggie1313** [comment]
No, it does. We definitely have them. We've been using them for two months.

**Comment by Redbeanw44602** [comment]
Sorry, English is not my first language. If it does exist, it may be temporarily broken in the new version, and CodeHz will fix them.

**Comment by Seggie1313** [comment]
That's why I opened an issue, for someone who knows more than I do to tell me if it's broken or not. Lol

**Comment by truaddict** [comment]
I can confirm that /warp list is broken for private warps.

**Comment by truaddict** [comment]
@codehz hi. Could you tell us if this bug is fixed in latest builds?

**Comment by Redbeanw44602** [comment]
The latest release has fixed this problem, I think this issue can be closed.

**Comment by Seggie1313** [comment]
Yes, it has. Thanks CodeHz!
