### ISSUE TITLE
Small bugs. 

### ISSUE THREAD

**Issue by ambiennt** [codehz/ElementZero#14]
Unexpected server .exe quitting within seconds after starting up. I noticed that if the server runs for over about 10 seconds, it wont crash. I am using windows 10 home 10.0.18363 with the x64 c++ redistributable installed.

The host cannot type the "%" character in-game, it just sends a blank message. 

The custom-name command does not have auto completion features upon loading the server IN SOME INSTANCES, unlike the vanilla commands where you can click "tab". Nothing showed after the "set" part of the command. This issue stopped happening after I disabled some other mods (built-in ones), but I figured it might be worth mentioning.

**Comment by Talark-Systems** [comment]
Have these been fixed?

**Comment by ambiennt** [comment]
> Have these been fixed?

I havent had trouble starting up or the custom name not autocompleting issue recently, but I still cannot type in the % sign as the host. It still sends a blank message.

**Comment by Talark-Systems** [comment]
The autocomplete issue may be worked on, I’m not sure, however, why do you need to type a % symbol into the host anyway? Or do you mean in the chat?

**Comment by ambiennt** [comment]
> The autocomplete issue may be worked on, I’m not sure, however, why do you need to type a % symbol into the host anyway? Or do you mean in the chat?

ohhhh. I mean in the minecraft, chat not the console window.

**Comment by Talark-Systems** [comment]
I’m not too sure why who’s happens, however, it may have something to do with the way this software interprets the player network packets. I’m honestly not too sure, although I am a programmer, making windows servers from scratch that run on Linux was never my strength.

I think @codehz should look at this, by the way, in a previous comment, I didn't mean it wasn't worth fixing, I was just wondering why you needed to type that character in the first place
