### ISSUE TITLE
Built In mods commands are broken

### ISSUE THREAD

**Issue by APersonOnGithub** [codehz/ElementZero#140]
When you type in any command such as /audit or another mod, it responds with something such as "commands.audit.success", and when check the description of the command it says "commands.audit.description"

**Comment by Kaludii** [comment]
You need to install the translation resource pack. https://github.com/Element-0/ElementZero/wiki/Installing-and-using-the-translation-resource-pack

**Comment by ambiennt** [comment]
theres no other way than to install that linked resource pack. Lang files are unfortunately only supplied by a resource pack

**Comment by elijahr2411** [comment]
As has been said above, you need to use the translation pack. https://github.com/Element-0/ElementZero/wiki/Installing-and-using-the-translation-resource-pack
