### ISSUE TITLE
Crash on Wine 5.0.2

### ISSUE THREAD

**Issue by GrimStride** [codehz/ElementZero#142]
I can't get ElementZero to work on my Linux server, it just crashes after a few seconds. I have tried 3 different versions of ElementZero: v0.1.0 testing, v0.1.0-4 and latest commit 363369b. But i always get this at the end of the output before crashing:
`2020-08-18 13:50:26 I [ModLoader] (Mod::Base:205) Init BasicAntiCheat`
`2020-08-18 13:50:26 I [ModLoader] (Mod::Base:205) Init ChatAPI`
`2020-08-18 13:50:26 I [ModLoader] (Mod::Base:205) Init CommandSupport`
`2020-08-18 13:50:26 I [ModLoader] (Mod::Base:205) Init FormUI`
`2020-08-18 13:50:26 I [ModLoader] (Mod::Base:205) Init Economy`
`2020-08-18 13:50:26 I [ModLoader] (Mod::Base:205) Init Essentials`
`2020-08-18 13:50:26 I [ModLoader] (Mod::Base:205) Init SpawnProtection`
`2020-08-18 13:50:26 V [ModLoader] (Mod::Base:224) Mod SpawnProtection is reloadable`
`wine: Call from 0x7bc6cf7c to unimplemented function KERNEL32.dll.RaiseFailFastException, aborting`
I even tried with a clean install of it with the mods disabled, but same error appears. I tried running the discontinued BedrockX, to check if it was a problem with my wine installation, but it ran flawlessly.
OS: Ubuntu 18.04
Using Lubuntu Core GUI
Wine version: 5.0.2
Command used: `WINEDLLOVERRIDES="vcruntime140_1,vcruntime140=n;mscoree,mshtml,explorer.exe,winemenubuilder.exe,services.exe,playplug.exe=d" WINEDEBUG=-all wine bedrock_server_mod.exe`
Running as root
And yeah, I'm pretty noob in Linux stuff.

**Comment by madeofstown** [comment]
Use docker.

**Comment by Redbeanw44602** [comment]
Use latest wine.
or try `wine64`

**Comment by GrimStride** [comment]
same error when using wine64. I'm using the latest wine stable version. Do you mean the latest development release of wine?

**Comment by Redbeanw44602** [comment]
What happened when you used `wine64` ?
Yes, use the latest development release.

**Comment by GrimStride** [comment]
Finally! It worked with the development branch. It seems it doesn't need all those dll overrides, I just placed vcruntime140, vcruntime140_1 and mscvcp140 on the folder, and used `wine64 bedrock_server_mod.exe` to run it.
Wiki should be edited to tell people they have to use the wine development branch.

**Comment by madeofstown** [comment]
Well if you do want to test out docker I made a more noob friendly tutorial on the forumshttps://elementzero.flarum.cloud/d/4-docker-install-instructions

**Comment by Redbeanw44602** [comment]
> Finally! It worked with the development branch. It seems it doesn't need all those dll overrides, I just placed vcruntime140, vcruntime140_1 and mscvcp140 on the folder, and used `wine64 bedrock_server_mod.exe` to run it.
> Wiki should be edited to tell people they have to use the wine development branch.

I'm glad you solved the problem. I think it's time to close this issue.
The latest wineHq release does not seem to require additional vcruntime, I think you can try it.
