### ISSUE TITLE
wine collapse

### ISSUE THREAD

**Issue by 530126162** [codehz/ElementZero#144]
![TL(D(TEW~Z2_9Y{1}PBCJ F](https://user-images.githubusercontent.com/70012803/90875538-e2bf1680-e3d3-11ea-9045-735a2613527f.png)

**Comment by 530126162** [comment]
No one knows？？？？

**Comment by 530126162** [comment]
help me!!!

**Comment by madeofstown** [comment]
Which instructions did you use to install and which build are you using.

**Comment by 530126162** [comment]
![image](https://user-images.githubusercontent.com/70012803/90999788-25623800-e5fa-11ea-8070-95f2d923a214.png)
This is installed
The wine version is 5.0.2

**Comment by 530126162** [comment]
> 您使用了哪些说明进行安装以及使用了哪些内部版本。

ElementZero-v0.1.0-6-win64
This is installed
The wine version is 5.0.2

**Comment by madeofstown** [comment]
Make sure that you have vcruntime140_1.dll in the same folder as bedrock_server_mod.exe

**Comment by 530126162** [comment]
> 确保在与bedrock_server_mod.exe相同的文件夹中有vcruntime140_1.dll

![image](https://user-images.githubusercontent.com/70012803/91000164-234ca900-e5fb-11ea-8b01-4e27a58ec696.png)
of course

**Comment by madeofstown** [comment]
Try docker method maybe.

**Comment by 530126162** [comment]
> Try docker method maybe.

I won't. do you have a detailed method

**Comment by madeofstown** [comment]
Wait. Are you using Windows?

**Comment by 530126162** [comment]
> 等待。您在使用Windows吗？

I won't. do you have a detailed method

**Comment by madeofstown** [comment]
For docker use this https://elementzero.flarum.cloud/d/27-linux-auto-install-script

**Comment by 530126162** [comment]
> 对于docker使用此https://elementzero.flarum.cloud/d/27-linux-auto-install-script

Thank you very much.

**Comment by madeofstown** [comment]
Glad I could help. 😁

**Comment by elijahr2411** [comment]
Closing because it seems the issue is solved. Feel free to reopen if it's not.
