### ISSUE TITLE
ScriptingSupport turns error

### ISSUE THREAD

**Issue by LavieGS** [codehz/ElementZero#148]
https://github.com/Weissnix4711/ElementZero-scripts
when i use the above scripts and start the server, i got following error:
![image](https://user-images.githubusercontent.com/46153563/91657414-aa1dec00-eafb-11ea-8692-2d5f3d019e1e.png)

ScriptingSupport and force-experimental-gameplay (and so) are true

there's a topic about Scripts not working on 1.16.1, is this still continuing?

EZ ver: v0.1.0-6 
BDS ver: 1.16.20.03
(Both are latest)

**Comment by AUG-Para** [comment]
Make sure to enable economy and chatAPI in custom.yaml.

**Comment by LavieGS** [comment]
Solved, thank you!
i should have made everything true, but i missed it, sorry.

**Comment by KenMizz** [comment]
is ur script working fine on the latest version?

**Comment by madeofstown** [comment]
> EZ ver: v0.1.0-6
BDS ver: 1.16.20.03
(Both are latest)
