### ISSUE TITLE
Can't get bedrock_server_mod.exe to open

### ISSUE THREAD

**Issue by Benhemoth** [codehz/ElementZero#149]
I keep getting an error.

Injected!
HealthCheck 00007FF716AE0000 00007FF716B8CE50
Failed to load base mod.
The specified module could not be found.

**Comment by Meisoner** [comment]
try chmod -R 777 /<bds+ez folder> or sudo docker run ...

**Comment by Benhemoth** [comment]
It was my fault. Didn't download Visual C++ thanks y'all!
