### ISSUE TITLE
How to run EZ by docker

### ISSUE THREAD

**Issue by echoker** [codehz/ElementZero#15]
> [root@ecs-0rZQB dist]# docker run --rm -ti -p 19132:19132/udp -v /root/ez/dist:/data codehz/wine:bdlauncher-runtime

> Injected!

> HealthCheck 0000000140000000 0000000140054870

> Failed to load base mod.

And I try many docker images,they are all back me the same error message.

My docker version is

> Docker version 19.03.8, build afacb8b

My Server is CentOS7.6 X64

Thank you.

**Comment by echoker** [comment]
And I do that in Ubuntu16 and 18,too

**Comment by codehz** [comment]
Try `find -name '*.dll' -exec chmod +x \{\} \;`
Some user report that dll is also need to be executable to allow map as executable memory, but I haven't tested

**Comment by echoker** [comment]
> 尝试
> 一些用户报告 dll 还需要可执行，才能允许映射作为可执行内存，但我还没有测试`find -name '*.dll' -exec chmod +x \{\} \;`

All dlls are 777,I do it before.

**Comment by codehz** [comment]
Other users have also reported the need for a new linux kernel to run...(I haven't tested old kernel, because all my linux machines are archlinux that no problem at all...

**Comment by IvanTurgenev** [comment]
i just set it up debian buster seems to work so far, with docker
