### ISSUE TITLE
commands dont work as expected

### ISSUE THREAD

**Issue by zurio-cmd** [codehz/ElementZero#156]
When i warp somewhere or ban or idk it always says like this
and command /home doesnt work at all
![Snimka zaslona (53)](https://user-images.githubusercontent.com/72339985/95955008-7c1b0f80-0dfc-11eb-96ec-64a072d32242.png)

**Comment by Weissnix4711** [comment]
Read the [wiki](https://github.com/Element-0/ElementZero/wiki/Installing-and-using-the-translation-resource-pack).

This is expected behaviour as you do not have the resource pack installed.

**Comment by zurio-cmd** [comment]
can u make a video tutorial cuz those steps are confusing asf
