### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by BttrThnDEV** [codehz/ElementZero#16]
When opening the MOD.exe the console appears to load fine, but hangs mid load.
Forcing the user to right click in the console window to fix the issue. Most of the time this results in a crash.

**Comment by codehz** [comment]
Any screenshot?

**Comment by BttrThnDEV** [comment]
Not really, the window looks normal, but when I right click, all the connections to the server start coming in and displaying at once
![image](https://user-images.githubusercontent.com/62577143/78876505-4a1b9180-7a04-11ea-8b46-9129ec6141f1.png)

**Comment by codehz** [comment]
it seems you enabled the "quick edit mode" for console program.. and in this mode, if you accidentally select a part of the text, it will cause the program to stop executing until you deselect it

**Comment by BttrThnDEV** [comment]
How do I disable this
