### ISSUE TITLE
1.16.100 update killed it

### ISSUE THREAD

**Issue by nobu-sh** [codehz/ElementZero#163]
outdated server, please fix

**Comment by ambiennt** [comment]
Yes, 1.16.100 is not compatible with 1.16.20 or 1.16.40.

On behalf of the element zero community, we all appreciate the work codeHZ has done so far for the software, and we all sincerely hope he continues working on it. Only time will tell though.

**Comment by Weissnix4711** [comment]
> Yes, 1.16.100 is not compatible with 1.16.20 or 1.16.40.

Shocker

Btw Exto and I (mostly Exto) are working on 1.16.100 update. See [here](https://github.com/Extollite/ElementZero/tree/patch-1)
