### ISSUE TITLE
Build failing on windows

### ISSUE THREAD

**Issue by elijahr2411** [codehz/ElementZero#170]
I'm attempting to build ElementZero. Upon trying to build bedrock_server_mod.pdb using Visual Studio lib.exe, I get the following error.

`LINK : fatal error LNK1189: library limit of 65535 objects exceeded`

I honestly have no clue what to do here. Google is no help. Any help would be appreciated

**Comment by Weissnix4711** [comment]
You must update `eatpdb.yaml` to filter more out. See [mine](https://github.com/Weissnix4711/ElementZero/tree/patch-1) or [exto's](https://github.com/Extollite/ElementZero/commits/1.16.100) forks.

All credit to exto who actually has a clue what he's doing, unlike me. :laughing:
