### ISSUE TITLE
Is there a way to run a pure bds server with Wine+Docker without mod ?

### ISSUE THREAD

**Issue by zxl777** [codehz/ElementZero#174]
run 'bds server for windows' in a linux dicker container with Wine.

Get BDS Server for windows 1.6.100
https://www.minecraft.net/en-us/download/server/bedrock

How To Run Any Windows CLI App in a Linux Docker Container
https://medium.com/better-programming/how-to-run-any-windows-cli-app-in-a-linux-docker-container-318cd49bdd25

The purpose of using BDS for windows is to minimize the CPU usage, so that the server has no lags.
If this version does not support mods, there should not be much reverse engineering and hacking.
This way we can keep up with Minecraft updates as soon as possible.

**Comment by Weissnix4711** [comment]
You cannot run BDS in wine. It requires many private DLLs. This is one of the reasons for this project.

![Screenshot from 2020-11-27 17-12-53](https://user-images.githubusercontent.com/42943391/100472284-e0a3dc80-30d3-11eb-8a24-ed1463e9f205.png)
