### ISSUE TITLE
Constant Server Crashes

### ISSUE THREAD

**Issue by BttrThnDEV** [codehz/ElementZero#18]
Random crashes, leading to some data loss, and very sad players.
 Log.db is attached

**Comment by codehz** [comment]
Where is the log.db?

**Comment by BttrThnDEV** [comment]
[log (2).zip](https://github.com/Element-0/ElementZero/files/4465714/log.2.zip)

**Comment by codehz** [comment]
This crash seems to have nothing to do with this project, and the information you provide is incomplete

**Comment by IvanTurgenev** [comment]
vanilla bds memory leak?

**Comment by Bluebotlaboratories** [comment]
Has the problem been solved? If so, I’m closing the issue

**Comment by Bluebotlaboratories** [comment]
Have there been any recent crashes, or has this been resolved?
