### ISSUE TITLE
Support for moving between worlds

### ISSUE THREAD

**Issue by mud3n8xk4ywqje5psfh76c** [codehz/ElementZero#20]
I would like to be able to move between worlds in "worlds" folder via one command or via scripting API. It’s just an indispensable feature, but the implementation is probably too complicated. I think others will agree with me.

**Comment by Talark-Systems** [comment]
Implementation would be very complicated, however, as this project gets better and moves out of the 'alpha' or 'beta' stage it is currently in, this feature may be added.

**Comment by Weissnix4711** [comment]
Currently the best method would be to host multiple different servers and use the transfer-server feature.

You could use this in scripts too, so you could change a player's server when they, say, interact with something, or really whatever you like.

**Comment by madeofstown** [comment]
Run 2 EZ instances using separe ports. /summon NPC and then use the command support in the NPC. 

Example command:
`/transferserver @p minecraft.server 19134`
