### ISSUE TITLE
Startup Error - Failed to load base mod.

### ISSUE THREAD

**Issue by Vl4dim1r** [codehz/ElementZero#21]
I received the following error after building/testing on my workstation, then transferring to my windows dedicated server.

`Injected!
HealthCheck 00007FF65D5C0000 00007FF65D614
Failed to load base mod.
The specified module could not be found.`

I have installed the vc_redist.x64. Are there any other dependencies that need to be installed, or any hard filesystem links that need to be updated?
https://i.gyazo.com/499a3ba5c42d94bd3298d8a56f71d6df.png

**Comment by codehz** [comment]
Can you post the screenshot of the folder's contents ?

**Comment by Vl4dim1r** [comment]
I was able to launch and play this on my workstation, uploaded the whole folder as it ran locally.

![](https://i.gyazo.com/b49e5438ead4fbf5d241c518a1109029.png)

**Comment by Vl4dim1r** [comment]
My fault, didn't reboot after installed vcredist.x64. Sorry to bother you, thanks for the quick reply!

**Comment by codehz** [comment]
@Vl4dim1r It seems normal, what's os are you using?
