### ISSUE TITLE
Documentation - where I can find it - how to work with it?

### ISSUE THREAD

**Issue by lemonka** [codehz/ElementZero#27]
As in title - where can I find any exmaples or documents desribing how to configure / use it?

**Comment by codehz** [comment]
See https://github.com/Element-0/ElementZero/wiki

**Comment by IvanTurgenev** [comment]
yeah documentation seems carce maybe open up somehow the wiki

**Comment by lemonka** [comment]
this wiki coversbasics of installation but lack of any information about configuration like how to use money, scripts, warp... built in Mods...

**Comment by mclauncherlinux** [comment]
> this wiki coversbasics of installation but lack of any information about configuration like how to use money, scripts, warp... built in Mods...

if that is the problem, you can easily host yourself a server check it out how it works and then open a pull request for the wiki with the description/docs ;)

**Comment by IvanTurgenev** [comment]
> > this wiki coversbasics of installation but lack of any information about configuration like how to use money, scripts, warp... built in Mods...
> 
> if that is the problem, you can easily host yourself a server check it out how it works and then open a pull request for the wiki with the description/docs ;)

can you open a pull request for the wiki?

**Comment by ambiennt** [comment]
there is no documentation for how the built in mods work and what they do. There are obvious ones like the basic anticheat mod, but nothing says what exactly it does, what it checks for, or how it works. More info on the mods would be nice.

**Comment by mclauncherlinux** [comment]
> > > this wiki coversbasics of installation but lack of any information about configuration like how to use money, scripts, warp... built in Mods...
> > 
> > 
> > if that is the problem, you can easily host yourself a server check it out how it works and then open a pull request for the wiki with the description/docs ;)
> 
> can you open a pull request for the wiki?

Ok, i have some time today. I will try to write a detailed description about all Mods how they work and how they could be used

**Comment by ambiennt** [comment]
> > > > this wiki coversbasics of installation but lack of any information about configuration like how to use money, scripts, warp... built in Mods...
> > > 
> > > 
> > > if that is the problem, you can easily host yourself a server check it out how it works and then open a pull request for the wiki with the description/docs ;)
> > 
> > 
> > can you open a pull request for the wiki?
> 
> Ok, i have some time today. I will try to write a detailed description about all Mods how they work and how they could be used

thank youuuuuuu

**Comment by mclauncherlinux** [comment]
> > > > > this wiki coversbasics of installation but lack of any information about configuration like how to use money, scripts, warp... built in Mods...
> > > > 
> > > > 
> > > > if that is the problem, you can easily host yourself a server check it out how it works and then open a pull request for the wiki with the description/docs ;)
> > > 
> > > 
> > > can you open a pull request for the wiki?
> > 
> > 
> > Ok, i have some time today. I will try to write a detailed description about all Mods how they work and how they could be used
> 
> thank youuuuuuu

ElementZero - Essential Commands/Mods

/balance - shows your own current money balance

/get-balance username - check money balance from a specific player. Players with space in the name need have to be entered like this /get-balance “ThisIsMy Username“
/tpa username - send tp request to players
/tpaccept - accept tp request
/tpdeny - disallow/deny tp request
/warp to (name) teleport to a warp point
/warp list - lists all warps
/warp del name - deletes your own warp
(OP)
/update-balance username - set/overwrite a players money balance
/global-warp set/del (name) - set/del a global warp - can be also allowed for non ops by enabling it in custom.yaml
/custom-name set/clear (name) - sets a player an alias/custom name in the server 

EZ Scripting

EZ offers an inbuilt scripting api similar to MoLang/Minecrafts scripting api. Also the commands above can be integrated in scripts, which means u currently can easily develop ur own shop UI or more that uses EZs inbuilt economy mod.

Vote Rewards: yes CodeHZ is also working on a vote reward mod (WIP): https://github.com/Element-0/SimpleVote

This is just a description about all essential commands, not about all mods. However, will write them too in the next few hrs

**Comment by ambiennt** [comment]
> > > > > > this wiki coversbasics of installation but lack of any information about configuration like how to use money, scripts, warp... built in Mods...
> > > > > 
> > > > > 
> > > > > if that is the problem, you can easily host yourself a server check it out how it works and then open a pull request for the wiki with the description/docs ;)
> > > > 
> > > > 
> > > > can you open a pull request for the wiki?
> > > 
> > > 
> > > Ok, i have some time today. I will try to write a detailed description about all Mods how they work and how they could be used
> > 
> > 
> > thank youuuuuuu
> 
> ElementZero - Essential Commands/Mods
> 
> /balance - shows your own current money balance
> 
> /get-balance username - check money balance from a specific player. Players with space in the name need have to be entered like this /get-balance “ThisIsMy Username“
> /tpa username - send tp request to players
> /tpaccept - accept tp request
> /tpdeny - disallow/deny tp request
> /warp to (name) teleport to a warp point
> /warp list - lists all warps
> /warp del name - deletes your own warp
> (OP)
> /update-balance username - set/overwrite a players money balance
> /global-warp set/del (name) - set/del a global warp - can be also allowed for non ops by enabling it in custom.yaml
> /custom-name set/clear (name) - sets a player an alias/custom name in the server
> 
> EZ Scripting
> 
> EZ offers an inbuilt scripting api similar to MoLang/Minecrafts scripting api. Also the commands above can be integrated in scripts, which means u currently can easily develop ur own shop UI or more that uses EZs inbuilt economy mod.
> 
> Vote Rewards: yes CodeHZ is also working on a vote reward mod (WIP): https://github.com/Element-0/SimpleVote
> 
> This is just a description about all essential commands, not about all mods. However, will write them too in the next few hrs

what about all the other mods, like audit, economy, no encryption, essentials, etc? I know the very basics of many of what you listed but nothing more, nothing sufficient enough for me to know how to properly use them, particularly with the blacklist mod. I still have no idea how to add someone to the list.

**Comment by mclauncherlinux** [comment]
blacklist mod = ban mod, not a whitelist, its used to ban players from your server

**Comment by ambiennt** [comment]
> blacklist mod = ban mod, not a whitelist, its used to ban players from your server

I know... im saying I dont know how to USE it- I know what a blacklist is

**Comment by IvanTurgenev** [comment]
now if the wiki was open?

**Comment by Talark-Systems** [comment]
I'm working on the wiki
