### ISSUE TITLE
Docker: failed to load base mod

### ISSUE THREAD

**Issue by lujo777** [codehz/ElementZero#3]
I tried to run the server fistly on Manjaro distribution, all was OK.
Next, following all instructions, I tried to run it on Debian and there is thrown error:

Failed to load base mod.

**Comment by codehz** [comment]
Check the permission of the files
(Owner should be uid=1000)

**Comment by lujo777** [comment]
I have all changed. Still not working

**Comment by codehz** [comment]
any screenshots or log?
about ls -alh folder and the whole `docker run` command

**Comment by lujo777** [comment]
![Screenshot_20200320_103547](https://user-images.githubusercontent.com/34795882/77144391-d0dcee80-6a96-11ea-98c9-e4fb50d0e6ef.png)
![Screenshot_20200320_103618](https://user-images.githubusercontent.com/34795882/77144396-d33f4880-6a96-11ea-9138-b6eff7aee80a.png)

**Comment by codehz** [comment]
oh, all the file is owned by root, that's why it cannot start
run 
`chown 1000:1000 -R .`

**Comment by mzdluo123** [comment]
I meet the same problem

![image](https://user-images.githubusercontent.com/23146087/77239961-7751fc80-6c1b-11ea-8f0f-7afacf616ced.png)

I have used `chown 1000:1000 -R .` in this folder

the same files can`t run on Windows too

**Comment by codehz** [comment]
@mzdluo123 (try use native linux wine 5.4

**Comment by codehz** [comment]
checking the kernel version, the minimal requirement is 4.19 (tested)

**Comment by codehz** [comment]
same as #4
