### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by niannianqi** [codehz/ElementZero#32]
I use Ubuntu's docker application to start the BDS server with EZ, but I can't load any dll plugin
![TIM图片20200420145200](https://user-images.githubusercontent.com/63998607/79722402-932de880-8316-11ea-9fb2-b7cbed995679.png)

**Comment by codehz** [comment]
All mods are disabled by default, you need enable them in custom.yaml

**Comment by niannianqi** [comment]
> 默认情况下，所有mod都是禁用的，您需要在custom.yaml中启用它们

oh,ok .but..How do I modify the file to open the plugin?

**Comment by niannianqi** [comment]
> All mods are disabled by default, you need enable them in custom.yaml

I'm sorry, I solved the problem ahead. But the chat information in Chinese is displayed as???? How to solve (I use xshell to connect ECS server and Shh)

**Comment by codehz** [comment]
generate locale for zh_CN.utf-8 (edit /etc/locale.gen, then run locale-gen
and set
LANG=zh_CN.utf-8
to /etc/environment
and reboot

**Comment by niannianqi** [comment]
> generate locale for zh_CN.utf-8 (edit /etc/locale.gen, then run locale-gen
> and set
> LANG=zh_CN.utf-8
> to /etc/environment
> and reboot

okay,thanks
