### ISSUE TITLE
show the time 

### ISSUE THREAD

**Issue by otocin** [codehz/ElementZero#33]
Is there any way to show the time on the console? It is the basic function of BDS, but Element-0 does not show the time.

Also, the time in the log file does not match the time zone of my computer. How can I change the time zone?

**Comment by codehz** [comment]
(the log in database is using UTC, and can be convert to localtime by datetime(time, 'localtime'))
And I will add back the time display in the next release

**Comment by otocin** [comment]
I'm really sorry, but how do I change from UTC to local time? I'm sorry I'm an layperson

**Comment by codehz** [comment]
@otocin It seems you're using some GUI program to browse database, so it won't be able to convert datetime automatically, but you can create a view for localtime
Execute `create view locallog as select session, datetime(time, 'localtime'), content from log;` in that database, and browse the locallog in UI
