### ISSUE TITLE
Unable to load Mod

### ISSUE THREAD

**Issue by linzjian666** [codehz/ElementZero#34]
I use windows's application, but cannot load any mods
![image](https://user-images.githubusercontent.com/63142068/80047267-8fc97580-853f-11ea-8c29-7c82fb822a99.png)

**Comment by linzjian666** [comment]
Why？

**Comment by itskiwi** [comment]
Make sure to edit the file "custom.yaml" and you will see that the Mods are disabled by default. Change false to true to any mods you will like then save and restart the server.

"custom.yaml" is located in the same directory of the server exe.

![mods](https://user-images.githubusercontent.com/2014821/80048907-6ae4ec00-84c6-11ea-90e9-bfe45cd74ab9.png)

**Comment by linzjian666** [comment]
Ok, I go to try

**Comment by linzjian666** [comment]
Okay, but still can't load custom mod

**Comment by HongyiMC** [comment]
@linzjian666 make sure you are running the mod.exe

**Comment by linzjian666** [comment]
OK

**Comment by linzjian666** [comment]
@HongyiMC It's will flash back
