### ISSUE TITLE
Vcpkg error: Cannot find definition for package `funchook`.

### ISSUE THREAD

**Issue by mud3n8xk4ywqje5psfh76c** [codehz/ElementZero#36]
When i try to install dependencies via vcpkg it throw exception: 
![Screenshot](https://user-images.githubusercontent.com/22578325/80784503-e5c49b80-8b85-11ea-852d-70656ef597e6.png)

I also tried to install funchook separately, but all is unsuccessful. The problem is clearly not in vcpkg.

**Comment by codehz** [comment]
Due to a bug in vcpkg(in latest version), the overlay-ports not working with relative path, you can hardcoded the path into vcpkg.txt

**Comment by mud3n8xk4ywqje5psfh76c** [comment]
Do you mean that?  This does not solve my problem.
![Screenshot](https://user-images.githubusercontent.com/22578325/80785738-f6771080-8b89-11ea-9662-011be07f183e.png)

**Comment by mud3n8xk4ywqje5psfh76c** [comment]
It looks like funchook is not provided by the vcpkg repository, it simply does not exist. Of the options, only manual compilation. Update vcpkg.txt if I am right.

**Comment by codehz** [comment]
> Do you mean that? This does not solve my problem.
> ![Screenshot](https://user-images.githubusercontent.com/22578325/80785738-f6771080-8b89-11ea-9662-011be07f183e.png)

the ports path is in ElementZero source path...

**Comment by mud3n8xk4ywqje5psfh76c** [comment]
Oh .. Everything is clear, thank you very much.
