### ISSUE TITLE
Mod commands never speak people words

### ISSUE THREAD

**Issue by Stephen-Hamilton-C** [codehz/ElementZero#37]
So, whenever I use a command that one of the mods supplies, I never get an actual result from the command. Instead I get things like `command.balance.success` rather than actually getting my balance. I've tried this with every command and they all do the same thing. Even /warp list returns `commands.warp.success.count.global`, which renders basically all the custom commands useless. I've encountered this on three different computers using the same installation technique as provided in the Wiki. All 3 are running Windows 10. I can't tell if this is an actual bug or just placeholders.

**Comment by codehz** [comment]
use https://github.com/Element-0/Translation (extract into development_resource_packs and enable in level

**Comment by Stephen-Hamilton-C** [comment]
Ok, I downloaded it and put the folder containing texts and packdata and such in the development_resource_packs and restarted the software, but how do I enable it in the level?

**Comment by codehz** [comment]
@Stephen-Hamilton-C edit world_resource_packs.json in level folder(you can generate it from client side if you don't know the format

**Comment by itskiwi** [comment]
What I did was added it on my offline world and then just copied over the world_resources.json files that it creates and the files over to my server world. 

Easier this way since it generates them for you

**Comment by nivranaitsirhc** [comment]
Here is the solution if you want to do it manually.
Step 1.
Create a file named world_behavior_packs.json & world_resource_packs.json

Step 2.
Open each pack's manifest and find the headers UID & version

Step 3.
add it to the world_resource_packs.json if its a resource pack or world_behavior_packs.json if its a behavior pack.

Step 4.
Follow this strict format in the json file. Array -> Object {pack_id: uid,version: Array.lenght 3}

example:
`
[{"pack_id" :"3ebe5826-c015-44eb-b3e7-368bf6387ab1","version" :[0,0,1]},{"pack_id" : "350eb579-fae2-4956-9bc8-0f1e89da415a","version" : [0,0,1]}]
`

Step 5.
add the two files in your world folder. Done!

**Comment by codehz** [comment]
PS: I have a plan to build a cli tools to generate those files

**Comment by nivranaitsirhc** [comment]
That would be really nice. Thanks

**Comment by Stephen-Hamilton-C** [comment]
Just did what @itskiwi said.

Created a world, exported it, modified the generated `world_resource_packs.json` file, stuck it into the server world, forced players to require texture packs from the world, and now players are able to see what their balance is and whatnot. Thanks! You're doing awesome work!

**Comment by IvanTurgenev** [comment]
OMG why is this not in the wiki
