### ISSUE TITLE
Custom Name Key

### ISSUE THREAD

**Issue by Stephen-Hamilton-C** [codehz/ElementZero#39]
I can't find anything anywhere that indicates what the `custom-name-key` is when trying to set a custom name. I keep getting syntax errors on that parameter when trying to set a custom name. What is it?

**Comment by codehz** [comment]
Ummm it should be autocompleted in game..
It is prefix|postfix

**Comment by Stephen-Hamilton-C** [comment]
Oh, I see it now. Thanks again!
