### ISSUE TITLE
No access to memory location.

### ISSUE THREAD

**Issue by RhythmNz** [codehz/ElementZero#4]
20.03 17:45:57 [服务器] 信息 wine-5.3
20.03 17:45:57 [服务器] 信息 Injected!
20.03 17:45:57 [服务器] 信息 HealthCheck 0000000140000000 0000000140054870
20.03 17:45:57 [服务器] 信息 Failed to load base mod.
20.03 17:45:57 [服务器] 信息 No access to memory location.

**Comment by codehz** [comment]
please provide more details

**Comment by RhythmNz** [comment]
使用wine5.3
跑在linux下
最新版游戏最新ez构建
在windows下可以跑的 直接复制粘贴到linux下
然后添加了
export WINEDLLOVERRIDES="vcruntime140_1,vcruntime140=n;mscoree,mshtml,explorer.exe,winemenubuilder.exe,services.exe,playplug.exe=d"  #必须
export WINEDEBUG=-all  #非必须，添加后可以避免输出太多调试信息
和这个dll运行库
wget https://ipfs.hertz.services/ipfs/QmYDqnHa7VeB9dqFczaR2K3Sj9qAr5JWNnYGtSg7WsR9r6/dlls.7z

**Comment by codehz** [comment]
我怀疑是权限问题，你检查下是不是有部分文件权限不对

**Comment by RhythmNz** [comment]
推荐文件设置什么权限比较好？
777？

**Comment by RhythmNz** [comment]
我一般除了可执行文件都是644

**Comment by RhythmNz** [comment]
请问是否能解决这个问题呢

**Comment by codehz** [comment]
（我觉得是wine的锅，但是我无法复现）

**Comment by codehz** [comment]
(检查一下内核版本

**Comment by RhythmNz** [comment]
应该使用什么内核版本

**Comment by codehz** [comment]
据了解4.19以上能正常运行(测试：5.6

**Comment by way-zer** [comment]
使用docker同样出现了该情况
![image](https://user-images.githubusercontent.com/15688938/78662792-a64abc80-7903-11ea-961a-6ea71fda2dfc.png)
启动提示相同
EDIT:
发现Mods内某一dll没有x权限，添加x权限后，问题解决

**Comment by codehz** [comment]
seems there is workaround: `find -name '*.dll' -exec chmod +x \{\} \;`

**Comment by way-zer** [comment]
Happened again with all dll execuable

**Comment by way-zer** [comment]
Happened again with all dll execuable when enable any one of mods
