### ISSUE TITLE
Mods?

### ISSUE THREAD

**Issue by Talark-Systems** [codehz/ElementZero#43]
Where can I find a collection of mods made for ElementZero?

**Comment by codehz** [comment]
There are some builtin mods, (disable by default), can be found in release package
A mods website is under construction

**Comment by Talark-Systems** [comment]
But is there a catalogue of player-made mods, such as a permissions mod?

**Comment by Talark-Systems** [comment]
I have created my own solution, by adding an issue to the template and then running a python scraper on the page, I should be able to make a mod catalogue.
