### ISSUE TITLE
Too much verbose

### ISSUE THREAD

**Issue by Talark-Systems** [codehz/ElementZero#44]
Is there a way to reduce verbose output so that it looks more like the vanilla server software:
e.g: Get rid of the stuff in brackets (DBStorage: ......)

**Comment by codehz** [comment]
in custom.yaml
```yaml
log-settings:
  format: "%6$s %1$c [%2$s] %5$s"
```

**Comment by Talark-Systems** [comment]
Could you please add to the wiki what each variable does: %6$ %1$, e.t.c.?

**Comment by codehz** [comment]
ok, soon

**Comment by Talark-Systems** [comment]
I'm going to experiment and hope to figure out what each one does!
