### ISSUE TITLE
Balance/Economy Permanent Scoreboard Display

### ISSUE THREAD

**Issue by GCPins** [codehz/ElementZero#46]
Is there a way to display your balance (from the Economy Mod) on screen (like the scoreboard command?).

**Comment by Talark-Systems** [comment]
This would be a really cool feature

**Comment by Extollite** [comment]
There is no such option currently. And no ETA for such features.

**Comment by codehz** [comment]
I will add this as script api, so you can update it in script

**Comment by GCPins** [comment]
Awesome! Thanks - I look forward to it!

**Comment by Weissnix4711** [comment]
You can see a (pretty bad) example of this [here](https://github.com/Weissnix4711/ElementZero-scripts/blob/master/scripts/info/scoreboard.js).

Bear in mind custom scoreboard is broken in the latest release, but will hopefully be fixed later on.
