### ISSUE TITLE
Missing pkg.tar.xz

### ISSUE THREAD

**Issue by Talark-Systems** [codehz/ElementZero#48]
The latest release (200504) is missing a pkg.tar.xz

**Comment by codehz** [comment]
because the contents is same as the other format, so it don't needed anymore...

**Comment by Talark-Systems** [comment]
What do you mean? Which folder should I extract and will it be the same for future releases?

**Comment by codehz** [comment]
> What do you mean? Which folder should I extract and will it be the same for future releases?

I mean the dist.tar.xz's contents is same as ElementZero-*-win64.zip/7z/tar.zst/sh etc..
(the top level folder's name is different, but you can use `tar xvf ElementZero-*-win64.tar.zst --strip-components 1` to bypass the top level folder

**Comment by Talark-Systems** [comment]
Ok thank you, I'll also update the wiki
