### ISSUE TITLE
Scripting API... but no documentation?

### ISSUE THREAD

**Issue by Talark-Systems** [codehz/ElementZero#49]
I can't find anything to do with the functions in the scripting API, even if you con't have any proper documentation could I at least see what each function does? Is there a file which contains every function?

**Comment by codehz** [comment]
https://github.com/Element-0/ElementZero/blob/master/ez.d.ts

**Comment by Talark-Systems** [comment]
Is that every function? Or does it exclude the vanila ones?
Also: Have you added the scoreboard balance system, or will it take more time (I understand if it does, programming is time-consuming)?

**Comment by codehz** [comment]
Nope, the balance api haven't added yet

**Comment by codehz** [comment]
the vanilla api won't be listed

**Comment by Bluebotlaboratories** [comment]
Okay, In the wiki, can I use [this](https://minecraft.gamepedia.com/Bedrock_Edition_beta_scripting_documentation) for the vanila part of the documentation?

**Comment by Talark-Systems** [comment]
But it **IS** compatible with the vanilla api, right?

**Comment by codehz** [comment]
yes
