### ISSUE TITLE
Mod docs

### ISSUE THREAD

**Issue by Talark-Systems** [codehz/ElementZero#52]
Please may you tell me what the functions for mods are (like you did for scripts, just send me to the file that does that)?

**Comment by codehz** [comment]
(will be added as dedicated readme files in builtin-mods

**Comment by Talark-Systems** [comment]
Are there repositories for them?

**Comment by codehz** [comment]
No, all builtin mods is placed in this repo(as subfolder in BuiltinMods

**Comment by Talark-Systems** [comment]
Ok
