### ISSUE TITLE
Ghidra?

### ISSUE THREAD

**Issue by Talark-Systems** [codehz/ElementZero#53]
I think I'm doing something wrong:
![image](https://user-images.githubusercontent.com/52605453/81304689-49166800-9075-11ea-820e-826124fa61a6.png)
(Feel free to point it out)

**Comment by codehz** [comment]
(load pdb in menu
and wait several hours...

**Comment by Talark-Systems** [comment]
O...
Oh my...
Uhh... hours? Does computer specs affect this?

**Comment by codehz** [comment]
![image](https://user-images.githubusercontent.com/13158903/81304926-4c7b1500-90b0-11ea-9adf-f9795aae5a24.png)
<- the progress

**Comment by codehz** [comment]
> O...
> Oh my...
> Uhh... hours? Does computer specs affect this?

absolutely, but I don't think there is any pc can decompile the whole file within 1 hour...
if you choose the linux version, it can take 1 days+ in normal pc...

**Comment by Talark-Systems** [comment]
Oh... does this support GPU acceleration?
