### ISSUE TITLE
Webhook/Mod for discord

### ISSUE THREAD

**Issue by GCPins** [codehz/ElementZero#54]
A mod that sends join/leave information (maybe even chat info idk) to a discord webhook/channel would be a great feature.

**Comment by lightyisreal** [comment]
Yeah, you're right

**Comment by ItzLightyHD** [comment]
@ItzLightyHD My comment xD

**Comment by Weissnix4711** [comment]
[Vellum for EZ](https://github.com/tomrhollis/vellum-for-EZ) will do this.

It also comes with other helpful features, like auto restart, backups, and mapping.

**Comment by GCPins** [comment]
Awesome.
