### ISSUE TITLE
Crash maybe hackers again

### ISSUE THREAD

**Issue by IvanTurgenev** [codehz/ElementZero#55]
```
Version: 1.14.60.5 with element-0 (200419)
OS: Windows
Server start: 2020-05-07 23:09:25 Greenwich S
Dmp timestamp: 2020-05-08 01:12:46 Greenwich S
Upload Date: 2020-05-08 01:12:46 Greenwich S
Session ID: 41ddfd8a-01d6-4f52-a0af-beb9a131e445
Commit hash: 37aca878ca1c71648b7646e6758b1cb97dba79b1
Build id: 3998270
CrashReporter Key: 876238ef-1f1e-3e90-960d-74a40b1a0fa0

Crash
I [SERVER] (CrashHelper::dumpCrashHandlerAppCrashLog:37)        at ItemStackBase::ItemStackBase[class ItemStackBase const &] (UnknownFile:?)                                                                                                 
        at bool Hopper::_isFullContainer[class BlockSource &,class Container &,int] (UnknownFile:?)
        at bool Hopper::_pushOutItems[class BlockSource &,class Container &,class Vec3 const &,int] (UnknownFile:?)
        at void HopperBlockActor::_tick[class BlockSource &,int] (UnknownFile:?)
        at void HopperBlockActor::tick[class BlockSource &] (UnknownFile:?)
        at void LevelChunk::tickBlockEntities[class BlockSource &] (UnknownFile:?)
        at void LevelChunk::tick[class BlockSource &,struct Tick const &] (UnknownFile:?)

abnormal program termination
```

**Comment by Talark-Systems** [comment]
Look at this thread: https://github.com/Element-0/ElementZero/issues/50

**Comment by IvanTurgenev** [comment]
> Look at this thread: #50

well thats not a fix but yeah i get what you mean, a temporary solution, but i use linux and docker already does that for me

**Comment by IvanTurgenev** [comment]
duplicate of what the other thread doesnt even have a crash log

**Comment by Talark-Systems** [comment]
If you say so, but why aren't you using anti-cheat?

**Comment by IvanTurgenev** [comment]
does the anticheat disables, what hacks?

**Comment by Talark-Systems** [comment]
Not sure... But it's anti-cheat, might as well try it

**Comment by IvanTurgenev** [comment]
i think the anticheat is to primitive, most likely the crashes are due to player inventory editing

**Comment by Talark-Systems** [comment]
Perhaps, but it could make a difference, it's not like you've tested it, besides, isn't primitive anti-cheat better than no anti-cheat?

**Comment by IvanTurgenev** [comment]
> Perhaps, but it could make a difference, it's not like you've tested it, besides, isn't primitive anti-cheat better than no anti-cheat?

will enable maybe it does work

**Comment by Bluebotlaboratories** [comment]
Should I close the other issue, as these two are alike?

**Comment by IvanTurgenev** [comment]
they would be alike if the crash report were the same

**Comment by truaddict** [comment]
AC is needed to prevent crashes from hacks. Also EZ was updated since then. So no need to keep this opened.
