### ISSUE TITLE
JavaScript API example

### ISSUE THREAD

**Issue by consllogluke** [codehz/ElementZero#56]
The JavaScript API looks great, but it would be nice if there was a simple example script that just shows off the very basics of how the API works, since the documentation is pretty limited currently.

**Comment by DevilLord41** [comment]
Have you checked this https://gist.github.com/codehz/89be99e13ecc177409ae3e715e72659b

**Comment by consllogluke** [comment]
Nope, I didn't see that. Thank you! :)
