### ISSUE TITLE
ElementZero discord

### ISSUE THREAD

**Issue by ambiennt** [codehz/ElementZero#60]
Im going to keep this short and sweet. Code HZ should make a discord dedicated to elementzero. It would make communication and information distribution about the server software much easier. I see no obvious reason why this idea would be problematic.

P.s. keep up the good work code <3

**Comment by Talark-Systems** [comment]
He already has a telegram

**Comment by ambiennt** [comment]
> He already has a telegram

telegrams arent as popular as discord though. anyways, could you direct me to the telegram?

**Comment by Talark-Systems** [comment]
https://t.me/ezloader

**Comment by ambiennt** [comment]
> https://t.me/ezloader

im gonna be honest, ive never heard of telegram until now. but thanks for the info.
