### ISSUE TITLE
Language pack

### ISSUE THREAD

**Issue by Talark-Systems** [codehz/ElementZero#61]
In the language pack there is a line that says:
~~~
accessibility.chat.howtoopen=§3Element§bZero §fby CodeHz, Translated by HongyiMC
~~~
Can we change it, or do we need to keep it?
And if we do change it, is there a way to show balance?

**Comment by codehz** [comment]
@Bluebotlaboratories Nope, it just a static string, cannot be dynamically, but sending a message after player join can be done in script

Yes, you can change it freely, but new line is impossible (

**Comment by Bluebotlaboratories** [comment]
Oh, ok, and what about the changing thing?

**Comment by codehz** [comment]
> Oh, ok, and what about the changing thing?
> Also: can I do newlines?

Yes, you can change it freely, but new line is impossible (
