### ISSUE TITLE
How do I view server logs?

### ISSUE THREAD

**Issue by ambiennt** [codehz/ElementZero#62]
I just had my first server crash ever, and this is very concerning for me. I would like to troubleshoot what went wrong, but I dont know how to do so without a log.

**Comment by codehz** [comment]
@nrss (check the internalData/DedicatedServer.txt at first

**Comment by ambiennt** [comment]
> @nrss (check the internalData/DedicatedServer.txt at first

it has nothing detailing the crash. Just autocompactions and when players join/leave

**Comment by ambiennt** [comment]
oh, I just realized that the text file resets every time the server is booted up. However, the text file didnt clear from the session before the crash even though I booted the server up after it. Maybe a suggestion is to have a log for each session? just an idea. Also, the only custom mods I have enabled (aside from education edition and experimental toggled) is essentials and noencryption. Could either of these potentially cause a crash?

**Comment by codehz** [comment]
@nrss Yeah, it is stored in log.db, sqlite3

**Comment by ambiennt** [comment]
[crash.txt](https://github.com/Element-0/ElementZero/files/4641922/crash.txt)
what does this mean? do you know what went wrong exactly?

**Comment by codehz** [comment]
> [crash.txt](https://github.com/Element-0/ElementZero/files/4641922/crash.txt)
> what does this mean? do you know what went wrong exactly?

How do you get it, it seems neither database or text file... You can just send the whole log.db

**Comment by ambiennt** [comment]
> > [crash.txt](https://github.com/Element-0/ElementZero/files/4641922/crash.txt)
> > what does this mean? do you know what went wrong exactly?
> 
> How do you get it, it seems neither database or text file... You can just send the whole log.db

I just copied the crash section into a text document to isolate it for you to better analyze. I will put the whole log in though. 
[log.txt](https://github.com/Element-0/ElementZero/files/4641966/log.txt)
(github doesnt support .db)

**Comment by codehz** [comment]
it seems to be a bds bug, and that's I cannot fix... hope 1.16 will fix it

**Comment by ambiennt** [comment]
> it seems to be a bds bug, and that's I cannot fix... hope 1.16 will fix it

ah, okay. Thank you anyways!!
