### ISSUE TITLE
Signs spam their commands when clicked

### ISSUE THREAD

**Issue by ub0nFPS** [codehz/ElementZero#63]
When clicking on a sign that an operator has attached a command to, it tends to spam, there should be a 1 second cool-down.
![photo_2020-05-18_12-18-22](https://user-images.githubusercontent.com/61366452/82252144-4e8c7180-9903-11ea-8710-387588b56ef6.jpg)

**Comment by ub0nFPS** [comment]
Same when attaching a command to a sign

**Comment by Talark-Systems** [comment]
Maybe it shouuld be added to some sort of config

**Comment by ub0nFPS** [comment]
Another issue, is commands can only be as long as the named stick item. and commands like
'setblock ~~-1~ redstone_block' will crash a server.

**Comment by codehz** [comment]
Try latest commit's ci artifact 
https://github.com/Element-0/ElementZero/actions/runs/108664869
And click dist (require github account, so you cannot copy the link to vps)

**Comment by Weissnix4711** [comment]
As sign command has been abandoned in the latest versions of ElementZero, this issue can probably be closed now.
