### ISSUE TITLE
getting this strange entity.player.name when using list

### ISSUE THREAD

**Issue by IvanTurgenev** [codehz/ElementZero#69]
```
list
There are 7/20 players online:
SAMUELKEOTHEKID, ClickedChip, xdGustavo133, pandagamert34, VERFETYBERRY, DEAGV8, entity.player.name                  
```
probably db related

**Comment by codehz** [comment]
seems custom-name nametag related

**Comment by IvanTurgenev** [comment]
also some players reported getting stuck when login, maybe deactivate custom-name meanwhile?, maybe you want to look the db files?

**Comment by codehz** [comment]
I will delete the nametag support in future, it is unstable and break everything

**Comment by IvanTurgenev** [comment]
maybe leave it on just for chat, and maybe edit player skins in a way that shows text instead

**Comment by ambiennt** [comment]
> I will delete the nametag support in future, it is unstable and break everything

That's unfortunate, because it could in theory be a useful tool. Will you keep prefixes and postfixes though? Also, maybe if it was possible, you could store the original name of the player even when his or her name is changed and use that as the string that is taggable. The original names are still displayed in the pause menu also.

**Comment by codehz** [comment]
@nrss only delete nametag(

**Comment by IvanTurgenev** [comment]
man being able to edit client code, man minetest is nice.

**Comment by ambiennt** [comment]
> I will delete the nametag support in future, it is unstable and break everything

im not sure if the nametag is the issue, but with the new release ive been having many problems with the server. I now have occasional crashes and the server freezing when attempting to auto-compact. If you know that these features are causing instability, then I would highly advise you to remove them.

**Comment by ub0nFPS** [comment]
@nrss 
My server is working fine after using the most recent action update... maybe update before making a large statement.

**Comment by ambiennt** [comment]
> @nrss
> My server is working fine after using the most recent action update... maybe update before making a large statement.

might I ask for you to elaborate on what you mean? I wasnt making a statement, I was making a suggestion, and the outcome of that suggestion would be contingent on the knowledge and experience of codeHZ himself. He himself stated that the custom nametag is "unstable" and is "break[ing] everything".

Second of all, I am using the most recent release (200517)- my reason for making the original comment was that I had no problems in 200504 and before. Maybe it would be better if we messaged about this on discord. Would you consider leaving your username?

**Comment by ub0nFPS** [comment]
@nrss 
https://github.com/Element-0/ElementZero/actions/runs/111050307

This is the proper update, where the issue has been fixed.

**Comment by ub0nFPS** [comment]
Download the dist

**Comment by ambiennt** [comment]
> @nrss
> https://github.com/Element-0/ElementZero/actions/runs/111050307
> 
> This is the proper update, where the issue has been fixed.

I think we werent on the same page with this issue. I was referring to the most recent release, not just the nametag problem. But thank you for letting me know. Did you have crashing issues before the action update though?

**Comment by ub0nFPS** [comment]
I did not, but I have felt better performance on the CPU side.

**Comment by ub0nFPS** [comment]
Are you running via windows?

**Comment by ambiennt** [comment]
> Are you running via windows?

yes, windows 10 build 18363.836 (latest version).

**Comment by ub0nFPS** [comment]
Odd, the issues you speak of haven't happened to me.

**Comment by ambiennt** [comment]
> Odd, the issues you speak of haven't happened to me.

given my situation and my higher-end specs, nothing else has changed other than the server software version for me. I dont believe this is an issue on my end. I just hope codehz works on stability improvements. (I dont mean this in a hateful way, im very grateful for what he has done, its just something id like to see him focus on).

**Comment by IvanTurgenev** [comment]
havent seen it since disabling custom-names, still think is a db issue since i updated some dbmight be uneven

**Comment by codehz** [comment]
test this artifact https://github.com/Element-0/ElementZero/actions/runs/111050307 (download dist in the page)

**Comment by IvanTurgenev** [comment]
> test this artifact https://github.com/Element-0/ElementZero/actions/runs/111050307 (download dist in the page)

ok will

**Comment by IvanTurgenev** [comment]
testing with  just replaced the dll

**Comment by IvanTurgenev** [comment]
i think i still see some steve floating without connection

**Comment by truaddict** [comment]
@IvanTurgenev is the problem still there? what about testing last successfully compiled version of EZ from Actions tab?
