### ISSUE TITLE
Spawn Protection, prevents players from accessing ender chests, chests, buttons, levers and doors.

### ISSUE THREAD

**Issue by BttrThnDEV** [codehz/ElementZero#7]
Title says it all!~

**Comment by lightyisreal** [comment]
It doesn't work for me

**Comment by Bluebotlaboratories** [comment]
I think that that's spawn protection's intended function (or at least one of them)

**Comment by codehz** [comment]
I will add some config option for that

**Comment by codehz** [comment]
It seems to be fixed in latest release
