### ISSUE TITLE
ChatAPI bug for content variable

### ISSUE THREAD

**Issue by TetsuyaGR** [codehz/ElementZero#71]
When i try print the content (for debugging) with the onChat event i always get "undefined". Here's my code

`import { onChat, sendBroadcast } from "ez:chat"; 
onChat((sender, content) => {
    console.log("ok works");
    console.log(content);
    console.log(sender);
    console.log(typeof(content));
});`

**Comment by SacriGrape** [comment]
onChat doesn't make two different objects (content, sender), it makes one.

**Comment by TetsuyaGR** [comment]
Aw yeah i understand that now it seems i have to do wrap["sender"] and wrap["content"] and to put only 1 parameter onChat
