### ISSUE TITLE
ScriptingAPI doesn't listen for vanilla events

### ISSUE THREAD

**Issue by TetsuyaGR** [codehz/ElementZero#72]
I'm trying to listen for player_attacked_entity event and i'm using the dedicated script folder but the event never gets called. In custom.yml i have `mod-enabled: true` and `mod-default-enabled: true` and 
```
Experimental:
    enabled: true
    force-experimental-gameplay: true
    education-feature: false
    debug-packs: false
```

Here's also the code

```
let aServerSystem = server.registerSystem(0, 0);
aServerSystem.initialize = function () {
    aServerSystem.listenForEvent("minecraft:player_attacked_entity", function(eventData) {
        console.log("player_attacked_entity event!");
        // Get the players armor container
        let playerArmor = aServerSystem.getComponent(eventData.data.player, "minecraft:armor_container");
        // Get the players helmet
        let playerHelmet = playerArmor.data[0];
        // Destroy the attacked entity if the player has a gold helmet equipped
        if (playerHelmet.item == "minecraft:golden_helmet") {
            aServerSystem.destroyEntity(eventData.data.attacked_entity);
        }
    });
};
```

**Comment by codehz** [comment]
the problem is system.initialize/update will not be invoked in scripts folder (but works in behavior packs)
workaround is put them in root level
(update can be replaced by setTimeout

**Comment by codehz** [comment]
(and you may need enable ScriptingSupport mod

**Comment by TetsuyaGR** [comment]
Yeah i forgot to mention i have enabled ScriptingSupport mod and it works perfectly fine with ez modules but not with vanilla, by root level you mean in the dedicated scripts folder? because it's in the main index.js file

EDIT: Nevermind i misunderstood, i just have to put them in the root level of the script (outside of the intialize function) Thank you for the help!
