### ISSUE TITLE
fall damage causing instant death.

### ISSUE THREAD

**Issue by ub0nFPS** [codehz/ElementZero#75]
When players fall, it causes an instant death. No idea what plugin or EZ issue is causing this.
(Newest Action)

**Comment by HongyiMC** [comment]
@BttrThnCode That's the anti cheat, it detects whenever there is a player that has no fall hacks, and kills them

**Comment by ub0nFPS** [comment]
Its obviously broken lol. It triggered on me, when I had none.

**Comment by HongyiMC** [comment]
@BttrThnCode are you in creative mode?

**Comment by ub0nFPS** [comment]
No, survival mode.

**Comment by truaddict** [comment]
@BttrThnCode could you confirm if bug is still present in last successfully compiled version of EZ (use Actions tab)?
P.S. I have never seen BAC being false-positive on this. All my players that were thrown off the world by BAC were hacking (NoFall cheat).
