### ISSUE TITLE
Query for the server?

### ISSUE THREAD

**Issue by lightyisreal** [codehz/ElementZero#8]
I'd like to add the server on server list, can i do this?

**Comment by codehz** [comment]
It is works in my machine...
Maybe you can try to use the official one

**Comment by HongyiMC** [comment]
@ItzLightyHD Yes

**Comment by ItzLightyHD** [comment]
@HongyiMC How?

**Comment by lightyisreal** [comment]
Ok, it works on https://minecraftpocket-servers.com.

**Comment by Legit4K** [comment]
Can it be fixed to work with https://mc-servers.xyz
