### ISSUE TITLE
External player cannot access server

### ISSUE THREAD

**Issue by Talark-Systems** [codehz/ElementZero#82]
External players cannot access my server

**Comment by IceCruelStuff** [comment]
I think you have to port forward

**Comment by Weissnix4711** [comment]
By external do you mean via the internet? Or on a different VLAN? I'm going to presume you mean internet.

Try joining from inside the LAN first, to make sure the server actually works.

Then, check firewall settings. And port forwarding. Check you're pointing UDP port 19132 or 19133 (or whatever you're using) to the correct machine. Either pointing to the correct IP, or Mac address. Idk what your setup is, so you'll have to figure that out.

If you've been assigned a fixed IP by your internet service provider, use that. Or check your dynamic DNS provider's settings.

If you are using a hostname, try using the IP directly. Might be an issue with your DDNS provider.

If it still isn't fixed, try calling up your ISP and asking them if they have an outage in your area. Or try pinging your network via the internet.

**Comment by Talark-Systems** [comment]
I have setup port forwarding (19132 and 19133) I have tried UDP and TCP-UDP, and yes, the server DOES work

**Comment by Weissnix4711** [comment]
TCP isn't necessary. My guess would be that it's a firewall issue. Or an issue with the hostname / DDNS provider.

As I said, I don't know your setup. I don't know which service you use. You'll have to figure that out yourself.

Good luck.

**Comment by Talark-Systems** [comment]
Firewall? and also, what do you need about my setup?

**Comment by IvanTurgenev** [comment]
na this happens all the time with android clients is prob not an ez bug but a shitty isp and "weak" andorid code

**Comment by Talark-Systems** [comment]
The client is using an iPad and no connection is shown on the server logs
Online mode is set to True

**Comment by IvanTurgenev** [comment]
> The client is using an iPad and no connection is shown on the server logs
> Online mode is set to True

then it is mobile clients samecode base, o it doest appear on the logs then it is a firewall thing where you hosting

**Comment by Talark-Systems** [comment]
There is a problem with the server software, if I run a website on the port (19132), my tool shows it as open, but when I'm running the server software, it says it is closed

**Comment by SacriPudding** [comment]
@Bluebotlaboratories Are you sure you have UDP forwarded and not TCP?

**Comment by Talark-Systems** [comment]
99.9% sure it's udp too:
![image](https://user-images.githubusercontent.com/52605453/84146774-1f75a580-aa54-11ea-967c-fadd217705d8.png)

**Comment by Talark-Systems** [comment]
Perhaps this is a bug with @codehz's software

**Comment by IvanTurgenev** [comment]
what you running on? have tried connecting outside local?

**Comment by Talark-Systems** [comment]
Local works, extranal is what doesn't, I'm running on ubuntu 18.04.4 LTS

**Comment by IvanTurgenev** [comment]
Are u using docker are u experienced on Linux? Check telegram

**Comment by Talark-Systems** [comment]
Using docker, not too good at linux

**Comment by KingTheGuy** [comment]
make sure the time on the pc running the server is correct.

**Comment by Talark-Systems** [comment]
1. Why would it matter?
2. It is

**Comment by KingTheGuy** [comment]
has to do with Microsoft authentication, but i guess that's not the problem. but try online-mode=false.

**Comment by Talark-Systems** [comment]
Tried that before
Ping and port open checks don't work either...

**Comment by Talark-Systems** [comment]
@codehz Could this be a problem with the docker command?

**Comment by IvanTurgenev** [comment]
yeah i am getting the same specially people on mobile data

**Comment by Weissnix4711** [comment]
@Bluebotlaboratories make sure when you run the docker container you open port 19132 on your network, and forward it to 19132 inside the container.

Do this with `docker run -p 19132:19132/UDP <image name>`
 Your entire docker run command should look similar to this: `docker run --rm -ti -p 19132:19132/udp -v <bds folder>:/data codehz/wine:bdlauncher-runtime`.

Also try running a completely stock version of BDS (without EZ) and seeing if you can access it like that.

**Comment by lyndsysimon** [comment]
> yeah i am getting the same specially people on mobile data

This rings a bell for me. I had trouble a while back getting some games to work on my iPad when I was using a VPN. It turned out, the VPN was routing the traffic over IPv6. Turning the VPN off routed the traffic over IPv4, and that worked.

My suspicion is that the port forwarding set up is IPv4 only, but that the client is attempting to connect via IPv6.

**Comment by IvanTurgenev** [comment]
got tired switched to minetest, m$ not for me
