### ISSUE TITLE
I have some questions and some suggestions...

### ISSUE THREAD

**Issue by lightyisreal** [codehz/ElementZero#9]
I like this modloader, because i can use it on Windows and because it has already some cool features.
My questions are:
- Why the spawn protection doesn't protect anything? And if possible, can i prevent players breaking only?
- Why is this tool a little bit complicated to use?
- Custom name and home are not working, can you fix them?

My suggestions are:
- Add the possibility to add mods much easily and to make a config for each them
- You should make a website for this project with a mod repository

I hope with these questions and suggestions i can improve the project.

**Comment by Talark-Systems** [comment]
1. To prevent players from breaking only, you can give them fatigue using a command:
/effect <nameOFPlayer> mining_fatigue 1000000 255 true
2. What tool?
3. Try now
4. I beleive the creator of ElementZero is working on it
5. The website is a work-in-progress

Keep in mind that programming something like this, with such functionality takes time, the creator of ElementZero is working as hard as they can with this project.

**Comment by Talark-Systems** [comment]
I have created my own solution for the mod problem, by adding an issue to the template and then running a python scraper on the page, I should be able to make a mod catalogue.
