### ISSUE TITLE
1.16 no release

### ISSUE THREAD

**Issue by jokey-carrot** [codehz/ElementZero#97]

**Comment by AlexWright1324** [comment]
True

**Comment by plutonium777** [comment]
@jokey-carrot Let's wait

**Comment by Weissnix4711** [comment]
Please see #99 for the current progress on the 1.16 update.

If you do wish to use a development version (potentially unstable) of ElementZero, then you can go to the [actions page](https://github.com/Element-0/ElementZero/actions). A new version is built every time there is a commit. You will looking for the `dist` artifact.
